### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#1]
## Epic: User Authentication and Management

As a **visitor** I want to **register for an account with a username, password, and email** so that **I can become a registered user and access features like creating my profile,  commenting on posts and forum and managing event participation**

## Acceptance criteria:

1. Visitors should be able to access a "Sign up" page.
2. The registration form should capture user information including username, email address, and password (with password confirmation for verification).
3. Upon successful registration, users should see a confirmation message on the screen.

## Tasks:

- [x] Develop a "Sign up" page.
- [x] Implement an user registration form with required fields (username, email, password).
- [x] Provide feedback of account successfully created.
