### ISSUE TITLE
Access Forum

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#11]
## Epic: Forum

As a **registered user** I can **access the forum** so that **I can participate in discussions.**

## Acceptance criteria:
1. Only registered users can access the forum.
2. Forum has categories and threads.

## Tasks:
- [ ] Create a forum homepage template.
- [ ] Display forum categories and threads.
- [ ] Restrict access to the forum to registered users.
- [ ] Test forum access restrictions.
