### ISSUE TITLE
View Events

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#14]
## Epic: Events

As a **registered user** I can **view a list of events** so that **I can know what events are happening**

## Acceptance criteria:

1. Users must be logged in to participate.
2. Events are displayed in a list format.
3. Events have details like date, time, and description.

## Tasks:

- [x] Create an events listing page template.
- [x] Display events.
- [x] Add details such as date, time, and description to events.
- [x] Test displaying events.
