### ISSUE TITLE
Manage Users

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#17]
## Epic: Admin Management

As an **admin** I can **view and manage user accounts** so that **I can maintain the website’s user base.**

## Acceptance criteria:

1. Admins can view a list of users.
2. Admins can deactivate or delete user accounts.

## Tasks:

- [x] Create a user management section in the admin dashboard.
- [x] Display user accounts.
- [x] Implement functionalities to deactivate and delete users.
- [x] Test user management functionalities.
