### ISSUE TITLE
Manage Comments

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#18]
## Epic: Admin Management

As an **admin**, I can **moderate comments on blog posts** so that **I can ensure discussions remain appropriate**.

## Acceptance criteria:

1. Admins can view and delete inappropriate comments.
2. Admins receive notifications of reported comments.

## Tasks:

- [x] Create a comment moderation section in the admin dashboard.
- [x] Display comments
- [x] Implement functionality to delete comments.
- [x] Test comment moderation functionalities.
