### ISSUE TITLE
Manage Forum

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#19]
## Epic: Admin Management

As an **admin**, I can **moderate forum threads and replies** so that **I can ensure discussions remain appropriate**.

## Acceptance criteria:
Admins can view and delete inappropriate threads/replies.
Admins receive notifications of reported threads/replies.

## Tasks:

- [ ] Create a forum moderation section in the admin dashboard.
- [ ] Display threads and replies.
- [ ] Implement functionality to delete threads and replies.
- [ ] Test forum moderation functionalities.
