### ISSUE TITLE
About page admin

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#26]
## Epic: About
As an **admin** I can ** create or update the about information** so that **I can make the it available to users**

## Acceptance criteria:
1. Have a form where I can enter text about the website
2. Have an edit button so I can update the information if I need to
3. Have a save button so I can save the changes made

## Tasks:

- [ ] Create an about page
- [ ] Add a form with a title and a textarea
- [ ] Add an edit button that presents the user with the text allowing the text to be edited
- [ ] Add

 an save button that submits the form
