### ISSUE TITLE
Landingpage

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#28]
## Epic: Homepage

As a **user** I can **see what the website is about as soon as I open the page** so that **can decide if it is interesting for me or not.**

## Acceptance criteria:

1. Have a hero image
2. Have text explaining what the website is about and who it is directed to
3. Have links redirecting for sign up and login

## Tasks:

- [x] Create a index.html
- [x] Find an appropriate image
- [x] Compose text to explain what the website is about
- [x] include links to sign up and login
