### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#29]
## Epic: Site navigation

As a **user** I can **search for content using keywords** so that **can easily find what I am looking for**

## Acceptance criteria:

1. Have a search field in all pages
2. Get the results for posts and content where the keywords are present

## Tasks:

- [x] Create a search field and button on the navigation bar
- [x] Handle the search on the backend
- [x] Check that the search finds all instances with the keyword used on the search
