### ISSUE TITLE
Useful links page

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#32]
## Epic: Sites content
As a **user** I can **click on links** so that **I can read information that is relevant to me**

## Acceptance criteria:

1. Page with useful links to be displayed to any users
2. Admin to be able to add links through the admin board
3. Link to be opened in a separate tab when clicked on

## Tasks:

- [x] Create a useful links page
- [x] Handle links additions by the admin
- [x] Check that the links open in a separate tab
