### ISSUE TITLE
Profile Management

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#4]
## Epic: User Profile

As a **registered user** I can **view and update my profile information** so that **my information is up to date**

## Acceptance criteria:

1. Users can view their profile details.
2. Users can update their personal information (name, e-mail, number of children (optional), children's dates of birth (optional), neighborhood (optional).

## Tasks:

- [x] Create a profile page.
- [x] Develop a form for updating profile information.
- [x] Implement form validation for profile updates.
- [x] Test viewing and updating profile information.
