### ISSUE TITLE
Read Single Post

### ISSUE THREAD

**Issue by pswhdev** [pswhdev/parenting_in_munich#8]
## Epic: Blog Posts

As a **visitor** I can **read the full content of a single blog post** so that **I can understand the content in detail.**

## Acceptance criteria:

1. Clicking a post title leads to the post detail page.
2. The post detail page displays the full content.

## Tasks:

- [x] Create a post detail page template.
- [x] Display a single post.
- [x] Test navigation from the post list to the post detail page.
